name: Docker CI

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            npm install
            npm run build:backend 
            npm run build:frontend
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/scytale:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/scytale:${{ github.sha }}

        - name: 'Deploy APP to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: scytale
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/scytale:${{ github.sha }}
            secure-environment-variables: APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }} ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }} ACCOUNT_KEY=${{ secrets.ACCOUNT_KEY }} APPINSIGHTS_APIKEY=${{ secrets.APPINSIGHTS_APIKEY }} APPINSIGHTS_APPID=${{ secrets.APPINSIGHTS_APPID }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: xuaps-scytale
            location: 'west europe'
            ports: 80 443
        - name: 'Deploy NGINX to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: scytale
            image: jonasal/nginx-certbot:latest
            azure-file-volume-share-name: nginx
            azure-file-volume-account-name: ${{ secrets.ACCOUNT_NAME }}
            azure-file-volume-account-key: ${{ secrets.ACCOUNT_KEY }}
            azure-file-volume-mount-path: /etc/nginx/user_conf.d
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: xuaps-scytale
            location: 'west europe'
            ports: 80 443
